Demonstrating the pdf build error
! Missing $ inserted.
<inserted text>
                $
l.3455 a & A_
             XN & A_YN\\

Error: LaTeX failed to compile RJafrocRocBook.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See RJafrocRocBook.log for more info.
Execution halted